version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: finance-management-api
    # command: ./main
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      PORT: "8080"
networks:
  default:
    name: api
